"""add recommendations

Revision ID: d5086fef0539
Revises: 6da7515673a2
Create Date: 2026-09-19 22:17:42.837417
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd5086fef0539'
down_revision: Union[str, Sequence[str], None] = '6da7515673a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('case_recommendations',
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('recommendation_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'recommendation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###